/*
  MOCK: Public landing reads editable JSON content from /content.
  This matches the requirement “самостоятельно редактировать сайт, подгружать файлы и фотографии”.
  In production, these JSON files can be generated by a CMS (Decap/WordPress/Strapi).
*/

const state = {
  settings: null,
  news: [],
  winners: [],
  galleries: {},
  activeYear: null,
  galleryCursor: 0,
  galleryPageSize: 12,
  lightbox: { items: [], index: 0 }
};

async function getJSON(url){
  const res = await fetch(url, { cache: 'no-store' });
  if(!res.ok) throw new Error(`Failed ${url}`);
  return res.json();
}

function el(tag, cls){
  const n = document.createElement(tag);
  if(cls) n.className = cls;
  return n;
}

function setText(id, value){
  const n = document.getElementById(id);
  if(n && value != null) n.textContent = value;
}

function setHref(id, value){
  const n = document.getElementById(id);
  if(n && value) n.href = value;
}

function iconDoc(){
  return `<svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><path d="M7 2h7l5 5v15a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2Zm7 1.5V8h4.5"/><path d="M8 12h8M8 16h8M8 20h6"/></svg>`;
}

function renderRules(rules){
  const grid = document.getElementById('rulesGrid');
  grid.innerHTML='';
  for(const r of rules){
    const a = el('a','tile');
    a.href = r.url || '#';
    a.target = '_blank';
    a.rel = 'noopener';
    const body = el('div','iconcard');
    const ic = el('div','icon');
    ic.innerHTML = iconDoc();
    const t = el('div');
    const h = el('div','tile-title'); h.textContent = r.title;
    const p = el('p','tile-text'); p.textContent = r.desc || '';
    t.appendChild(h); t.appendChild(p);
    body.appendChild(ic); body.appendChild(t);
    a.appendChild(body);
    grid.appendChild(a);
  }
}

function renderNews(items){
  const grid = document.getElementById('newsGrid');
  grid.innerHTML='';
  for(const n of items){
    const a = el('a','tile');
    a.href = `news/post.html?slug=${encodeURIComponent(n.slug)}`;

    if(n.cover){
      const img = el('img','tile-img');
      img.src = n.cover;
      img.alt = n.title;
      img.loading = 'lazy';
      a.appendChild(img);
    }

    const b = el('div','tile-body');
    const h = el('div','tile-title'); h.textContent = n.title;
    const p = el('p','tile-text'); p.textContent = n.excerpt || '';
    const m = el('div','tile-meta');
    const d = el('span'); d.textContent = n.date || '';
    const tag = el('span'); tag.textContent = n.tag || '';
    m.appendChild(d); m.appendChild(tag);
    b.appendChild(h); b.appendChild(p); b.appendChild(m);
    a.appendChild(b);
    grid.appendChild(a);
  }
}

function renderWinners(items){
  const track = document.getElementById('wTrack');
  track.innerHTML='';
  for(const w of items){
    const card = el('div','w-card');
    const year = el('div','w-year'); year.textContent = w.year;
    const img = el('img','w-photo'); img.src = w.photo; img.alt = w.name; img.loading='lazy';
    const name = el('div','w-name'); name.textContent = w.name;
    const city = el('div','w-city'); city.textContent = w.city || '';
    const team = el('div','w-team'); team.textContent = (w.team || []).join(' · ');
    card.appendChild(year); card.appendChild(img); card.appendChild(name); card.appendChild(city); card.appendChild(team);
    track.appendChild(card);
  }
}

function renderYearTabs(years){
  const tabs = document.getElementById('yearTabs');
  tabs.innerHTML='';
  years.sort((a,b)=>Number(b)-Number(a));
  for(const y of years){
    const b = el('button','tab');
    b.type='button';
    b.textContent = y;
    b.classList.toggle('active', String(y)===String(state.activeYear));
    b.addEventListener('click', ()=>{
      state.activeYear = y;
      state.galleryCursor = 0;
      drawGallery();
      renderYearTabs(years);
    });
    tabs.appendChild(b);
  }
}

function openLightbox(items, index){
  state.lightbox.items = items;
  state.lightbox.index = index;
  const lb = document.getElementById('lightbox');
  const img = document.getElementById('lbImg');
  const cap = document.getElementById('lbCap');
  const it = items[index];
  img.src = it.src;
  img.alt = it.alt || '';
  cap.textContent = it.caption || '';
  lb.hidden = false;
}
function closeLightbox(){
  document.getElementById('lightbox').hidden = true;
}
function stepLightbox(dir){
  const items = state.lightbox.items;
  let i = state.lightbox.index + dir;
  if(i<0) i = items.length-1;
  if(i>=items.length) i = 0;
  state.lightbox.index = i;
  openLightbox(items, i);
}

function drawGallery(){
  const grid = document.getElementById('galleryGrid');
  grid.innerHTML='';
  const year = state.activeYear;
  const items = (state.galleries[year]?.photos || []).map((src, idx)=>({
    src,
    alt: `Фото ${year} #${idx+1}`,
    caption: state.galleries[year]?.title ? `${state.galleries[year].title} · ${year}` : String(year)
  }));

  const slice = items.slice(0, state.galleryCursor + state.galleryPageSize);
  state.galleryCursor = slice.length;

  for(let i=0;i<slice.length;i++){
    const it = slice[i];
    const a = el('a','tile');
    a.href = it.src;
    a.addEventListener('click', (e)=>{
      e.preventDefault();
      openLightbox(slice, i);
    });
    const img = el('img','tile-img');
    img.src = it.src;
    img.alt = it.alt;
    img.loading='lazy';
    a.appendChild(img);
    grid.appendChild(a);
  }

  const btn = document.getElementById('loadMore');
  btn.disabled = state.galleryCursor >= items.length;
  btn.textContent = btn.disabled ? 'Больше нет фото' : 'Показать ещё';
}

function renderSponsors(items){
  const grid = document.getElementById('sponsorsGrid');
  grid.innerHTML='';
  for(const s of items){
    const a = el('a','sponsor');
    a.href = s.url || '#';
    a.target = '_blank';
    a.rel = 'noopener';
    const img = el('img');
    img.src = s.logo;
    img.alt = s.name;
    img.loading='lazy';
    a.appendChild(img);
    grid.appendChild(a);
  }
}

function setMode(mode){
  const isNews = mode === 'news';
  document.getElementById('modeNews').setAttribute('aria-pressed', String(isNews));
  document.getElementById('modeWinners').setAttribute('aria-pressed', String(!isNews));

  document.getElementById('newsGrid').hidden = !isNews;
  document.getElementById('winners').hidden = isNews;

  setText('newsTitle', isNews ? 'Новости' : 'Победители');
  setText('newsSub', isNews ? 'Последние обновления и анонсы.' : 'Архив победителей по годам.');
}

async function main(){
  state.settings = await getJSON('content/settings.json');

  // apply settings into UI
  setText('orgName', state.settings.organizer.name);
  setText('orgTagline', state.settings.organizer.tagline);
  setText('orgShort', state.settings.organizer.short);
  setText('footerOrg', state.settings.organizer.legal);
  setText('footerContacts', state.settings.organizer.contacts);
  setHref('vkLink', state.settings.social.vk);
  setHref('tgLink', state.settings.social.tg);
  setHref('pdLink', state.settings.links.pd);
  setHref('termsLink', state.settings.links.terms);

  setText('eventKicker', state.settings.event.kicker);
  setText('eventName', state.settings.event.name);
  setText('eventYear', state.settings.event.year);
  setText('eventDesc', state.settings.event.description);
  setText('inviteLine', state.settings.event.inviteLine);
  setText('eventDate', state.settings.event.date);
  setText('eventTime', state.settings.event.time);
  setText('eventAddress', state.settings.event.address);
  setText('eventCity', state.settings.event.city);
  setText('eventStatus', state.settings.event.status);

  setHref('applyBtn', state.settings.apply.primaryUrl);
  setHref('applyBtn2', state.settings.apply.primaryUrl);
  setHref('tgApplyBtn', state.settings.apply.tgUrl);

  // rules
  renderRules(state.settings.rules);

  // news
  state.news = await getJSON('content/news/index.json');
  renderNews(state.news.items);

  // winners
  state.winners = await getJSON('content/winners.json');
  renderWinners(state.winners.items);

  // gallery
  state.galleries = await getJSON('content/gallery.json');
  const years = Object.keys(state.galleries).filter(k=>k!=='_meta');
  state.activeYear = state.galleries._meta?.defaultYear || years.sort((a,b)=>Number(b)-Number(a))[0];
  renderYearTabs(years);
  drawGallery();

  // sponsors
  const sponsors = await getJSON('content/sponsors.json');
  renderSponsors(sponsors.items);

  // mode switch
  document.getElementById('modeNews').addEventListener('click', ()=>setMode('news'));
  document.getElementById('modeWinners').addEventListener('click', ()=>setMode('winners'));

  // winners nav
  const track = document.getElementById('wTrack');
  document.getElementById('winPrev').addEventListener('click', ()=>track.scrollBy({left:-340,behavior:'smooth'}));
  document.getElementById('winNext').addEventListener('click', ()=>track.scrollBy({left:340,behavior:'smooth'}));

  // gallery load more
  document.getElementById('loadMore').addEventListener('click', ()=>drawGallery());

  // lightbox
  document.getElementById('lbClose').addEventListener('click', closeLightbox);
  document.getElementById('lbX').addEventListener('click', closeLightbox);
  document.getElementById('lbPrev').addEventListener('click', ()=>stepLightbox(-1));
  document.getElementById('lbNext').addEventListener('click', ()=>stepLightbox(+1));
  document.addEventListener('keydown', (e)=>{
    const lb = document.getElementById('lightbox');
    if(lb.hidden) return;
    if(e.key==='Escape') closeLightbox();
    if(e.key==='ArrowLeft') stepLightbox(-1);
    if(e.key==='ArrowRight') stepLightbox(+1);
  });

  // default mode
  setMode(state.settings.ui.defaultMode || 'news');
}

main().catch(err=>{
  console.error(err);
  alert('Не удалось загрузить контент. Проверьте, что проект запущен через локальный сервер (не file://).');
});
